# Generated by Django 4.0.3 on 2022-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('is_guest', models.BooleanField(default=True, verbose_name='손님 여부')),
            ],
            options={
                'verbose_name': '멤버',
                'verbose_name_plural': '멤버 리스트',
                'ordering': ['is_guest', 'id'],
            },
        ),
    ]
